# Generated by Django 5.0.6 on 2024-05-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnergoMap', '0002_fddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ID_FD', models.IntegerField()),
            ],
        ),
    ]
